version: 0.0
os: linux


files:
  # 인스턴스에 복사할 디렉토리 경로
  - source:  /
    # 인스턴스에서 파일이 복사되는 위치
    destination: /home/ubuntu/app
    # 복사할 위치에 파일이 있는 경우 대체
    overwrite: yes

permissions:
  # 권한이 지정되는 파일 또는 디렉터리
  - object: /
    # 매칭되는 패턴에만 권한 부여
    pattern: "**"
    # object 의 소유자
    owner: ubuntu
    # object 의 그룹 이름
    group: ubuntu

hooks:
  # location: hooks 에서 실행할 스크립트 위치
  # timeout (optional): 스크립트 실행에 허용되는 최대 시간이며, 넘으면 배포 실패로 간주됨
  # runas (optional): 스크립트를 실행하는 사용자
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: ubuntu