spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 10MB # 최대 파일 업로드 크기
      max-request-size: 20MB # 최대 요청 크기
  web:
    resources:
      add-mappings: false
  jackson:
    time-zone: Asia/Seoul

  datasource:
    url: ENC(02fSnDdfn79NCTOoK+S//uZdtNl8qaGV4PFvsyZNmX3TD5M3Jp00M5WeFkhW4viJqymYgE2eOOMRH+RuuwjhNYHZgl+tbEzXP7Cf6BecVDlKkx63jLWOlCTFqh9Wp3TH)
    username: ENC(D6JUma7QtjPy+lHtuSduCA==)
    password: ENC(drzypccSCkhUOUOSVKnd0w4RQmgbgDgP)
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #       show_sql: true
        format_sql: true
  logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace #??? ?? 2.x, hibernate5
# org.hibernate.orm.jdbc.bind: trace #??? ?? 3.x, hibernate6

security:
  jwt:
    secret-key: ENC(cp8bU+SpbqCdUlouP1Lz/6mjmP+MLCPZ6Lr6yVOtZK0=) # 길게 바꿔서 넣기
    password-suffix: ENC(J6v3Kqog2zLTL0lvTVzLmA==)

chatgpt:
  model: gpt-4-1106-preview
  secret-key: ENC(OxS1jI1w5YIEYa7qyP0JRYI60NLs5KlLbo3r13ddR8TFAiEqXthYVr7q1y8P7tfsAc+SSCyd6fP7IOnX/S+yYFgACyyyrjCy)
  url: https://api.openai.com/v1/chat/completions

sunoai:
  url: ENC(1ISU6jhStXzYpnYjhVijWAv62XJ2pAtozQ6HECCBOwOw/PC+Iatrsw==)

kakao:
  url: https://kapi.kakao.com/v2/user/me

apple:
  auth:
    url: https://appleid.apple.com
  grant-type: authorization_code
  client-id: ENC(m3P4br63HKTiTxhy2nUx4gt5u9pOs33VGhogz/7KPR4=)
  key-id: ENC(CFTZK07ND1a+/5hLiwBg/y+WJypH/xsV)
  team-id: ENC(68d/73suwhVi1hTYjiv2pzKwC0741IBL)
  audience: https://appleid.apple.com
  private-key: ENC(Zl3fXPFpInV8mw/blG70dKQmhmd530ec+eUxKiu8annFmbjMgVqod0pZSyyeLZtrRbB3/RQIcpazvrIQ2OvRt8vvx4Ruv2kjmG46xHhBeDpksKnClvoWGqslsnwwYFi/btBLbbr55Yzq90yWAjn25XggJ24gcvndqdadKqAeEMKpmoE9JPj47R8xI/D69pg5oDolhlvyDX1cKn1cCkx/3e3WA8HXb/pM09L6UpboAYVHzP0CJp1rFyqcng7tTkI1YzmBfCzxDLsEYv8tINLCxy3BLb9+hJcE)

firebase:
  bucket-name: ENC(hTBtA6V7PdGXLWKpzveJebAsdgbB7WQgfwog2dP4kdIQiEhVkpgqeA==)

cloud:
  aws:
    credentials:
      accessKey: ENC(2Isv6ut7fEpy0pi0K4rC+nSdG0eSAepknXHkF5NK7aE=)
      secretKey: ENC(ItFge19ymmE0wR77YBS4+omrMfKM2PFSTV9fiSwYdQ3NPV2BC9fLnkOadKyiKigDrjpRgzQ+WUQ=)
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: ENC(oadvsbNwYzycADFmJH36kmVdMSs/1+sT90N0FQ63NGY=)
    cloudfront:
      domain: cdn.chewthecud.site
      key-pair-id: ENC(VnG9qeHZS28J1CWh0MNHo01IDuSPFRM6dHSa8dqF3pYKO8AEpKLf3qkZ/Lm6gFrr)
      private-key-file: ENC(kPGYKIzKFMfJosFQ5P1mWOr3jxHQKRFDFH/GyaoTREbzoY1iMiIrEA==)