spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 10MB # 최대 파일 업로드 크기
      max-request-size: 20MB # 최대 요청 크기
  web:
    resources:
      add-mappings: false
  jackson:
    time-zone: Asia/Seoul

  datasource:
    url: ENC(qnZGBAjpxVbCRLZv8cf3gtIvi5rH0MZFtfXGkkYOcP+YbcAyPY48HkdPPb5XouR3ky2xZyE7AmUHkLlsZMLmcPGFYlBL6qNBY9xe1Lure6Cygm+Fhdx5QsJKeu8U5+ye)
#    url: ENC(02fSnDdfn79NCTOoK+S//uZdtNl8qaGV4PFvsyZNmX3TD5M3Jp00M5WeFkhW4viJqymYgE2eOOMRH+RuuwjhNYHZgl+tbEzXP7Cf6BecVDlKkx63jLWOlCTFqh9Wp3TH)
    username: ENC(D6JUma7QtjPy+lHtuSduCA==)
    password: ENC(drzypccSCkhUOUOSVKnd0w4RQmgbgDgP)
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #       show_sql: true
        format_sql: true
  logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace #??? ?? 2.x, hibernate5
# org.hibernate.orm.jdbc.bind: trace #??? ?? 3.x, hibernate6

security:
  jwt:
    secret-key: ENC(cp8bU+SpbqCdUlouP1Lz/6mjmP+MLCPZ6Lr6yVOtZK0=) # 길게 바꿔서 넣기
    password-suffix: ENC(J6v3Kqog2zLTL0lvTVzLmA==)

chatgpt:
  model: gpt-4-turbo
  secret-key: ENC(gIEgGH1KOl9TWH2yDT+0PI45pg9+U2lqQoOTMCY7oqsN4RgUdykz38NwD3XHNO8Fy3aKEZ1TDQ38Q29vYSPbhjgW3SKLRtYz)
  url: https://api.openai.com/v1/chat/completions

sunoai:
  url: https://apibox.erweima.ai
  secret-key: 8f13c3e885bb6675a157e9ef14eb58cc
#  secret-key: ENC(P6iepJ++d6Ua6UCoJwn67GH01Ma5WZY2Dqc35dE8Tmfg1hBEo6HsdW/ZqUFJVZaC)

kakao:
  url: https://kapi.kakao.com/v2/user/me

apple:
  auth:
    url: https://appleid.apple.com
  grant-type: authorization_code
  client-id: ENC(edu2ooDuyWCeC1y2Kas0ORHaWUSiRJ/KziJ753cLQsI=)
  key-id: ENC(xiv69/9h6HOatxWDNgSzL1N6Vh7pnowS)
  team-id: ENC(68d/73suwhVi1hTYjiv2pzKwC0741IBL)
  audience: https://appleid.apple.com
  private-key: ENC(n5Juuqw3/BhOZ7dNBvJP/VaXLhW7XxCYofkwBhV8EsMr2Em2BMh+BfLzOMMIHTCVvtjsBI9Vnp1sm3TFOG3pgIzDyn002kQ2BkZcKp4WplK0PTpEtw0OHrukm53ZdOMLxUu6nCEekql6LSZjNn6cBQDbVsZz8QIz/t7zP+uwzmHIXJb4kgQ45d4bYlsHZ4JaMezlONKnDW55b4g1MDNdfq5wYb3gsyRuHrb0zUtZvleR0HPHuhAQNm8eeol9S9f7aAthEAsbC/xhH4FSJUw63vi2OKu+6fQ8)

google:
  url: ENC(LitNjbqTFOwpg179buuc5vm1FBZAABksa8GsM0Nlv/uiXmJmQWwlaavbcosE02UhcMa6ctfk9omefnTxrAmJ2A==)

firebase:
  bucket-name: ENC(hTBtA6V7PdGXLWKpzveJebAsdgbB7WQgfwog2dP4kdIQiEhVkpgqeA==)

cloud:
  aws:
    credentials:
      accessKey: ENC(x7+/ObKaiEM4u7kMo+bjCftRM/4Lq31Qzh1eX5ucYDk=)
      secretKey: ENC(wTzsktpQ1OaeAVXG6HZLDw0bINkgTcONCu2AyveDzFC/JgV21cE23F1EhkyuRxzr2D1+DNoe4D4=)
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: ENC(oadvsbNwYzycADFmJH36kmVdMSs/1+sT90N0FQ63NGY=)
    cloudfront:
      domain: cdn.chewthecud.site
      key-pair-id: ENC(VnG9qeHZS28J1CWh0MNHo01IDuSPFRM6dHSa8dqF3pYKO8AEpKLf3qkZ/Lm6gFrr)
      private-key-file: ENC(kPGYKIzKFMfJosFQ5P1mWOr3jxHQKRFDFH/GyaoTREbzoY1iMiIrEA==)