spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 10MB # 최대 파일 업로드 크기
      max-request-size: 20MB # 최대 요청 크기
  web:
    resources:
      add-mappings: false
  jackson:
    time-zone: Asia/Seoul

  datasource:
    url: jdbc:mysql://daytune-db-dev.cn6y6ga82851.ap-northeast-2.rds.amazonaws.com:3306/daytune
    username: root
    password: cbejzjem2023!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #       show_sql: true
        format_sql: true
  logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace #??? ?? 2.x, hibernate5
# org.hibernate.orm.jdbc.bind: trace #??? ?? 3.x, hibernate6

security:
  jwt:
    secret-key: common-secret-key # 길게 바꿔서 넣기
    password-suffix: daytune

chatgpt:
  model: gpt-4-1106-preview
  secret-key: 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
  url: https://api.openai.com/v1/chat/completions

sunoai:
  url: http://3.35.117.11:3000/api

kakao:
  url: https://kapi.kakao.com/v2/user/me

apple:
  auth:
    url: https://appleid.apple.com
  grant-type: authorization_code
  client-id: com.chewthecud.daytune
  key-id: KP2729287P
  team-id: 5WAUHBZJ8Z
  audience: https://appleid.apple.com
  private-key: MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgzRRDtyK0dKbQybMyMV8jw863ODUpyt+j6tRtdQ091PqgCgYIKoZIzj0DAQehRANCAAS4L3ht+UpWcjJNHkozue494jufo265Wrg5K6L1ZxLrsE70cPWiPKBxvadT68Kvfvj4d/vTG7B3btc2YHpUuK/Z

firebase:
  bucket-name: daytune-3722b.appspot.com

cloud:
  aws:
    credentials:
      accessKey: AKIA6GBMES42FVAAMYOK
      secretKey: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: daytune-share-url-s3
    cloudfront:
      domain: cdn.chewthecud.site
      key-pair-id: dbc72f9c-1660-47b1-9948-70b6a9b397fd
      private-key-file: pk-APKA6GBMES42C3BHDSO7.pem